// <auto-generated />
namespace ShopingStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class database_creation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(database_creation));
        
        string IMigrationMetadata.Id
        {
            get { return "202105291712120_database_creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
